spring.application.name=jdata-02

spring.datasource.url=jdbc:postgresql://localhost:5432/jdata
spring.datasource.username=jdatastudent
spring.datasource.password=123456

spring.sql.init.mode=always
spring.datasource.continue-on-error=true
