CREATE TABLE CUSTOMERS (
 id SERIAL PRIMARY KEY,
 name VARCHAR(50), surname VARCHAR(50), age INTEGER,
 phone_number VARCHAR(50)
);

CREATE TABLE ORDERS (
 id SERIAL PRIMARY KEY,
 date DATE,
 customer_id INTEGER,
 product_name VARCHAR(50),
 amount INTEGER,
 FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(id)
);
